<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <LangVersion>10</LangVersion>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <RootNamespace>FivePRS.Police</RootNamespace>
    <AssemblyName>FivePRS.Police.net</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(MSBuildThisFileDirectory)..\bin\client\</OutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CitizenFX.Core.Client" Version="1.0.26803" ExcludeAssets="runtime" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FivePRS.Core\FivePRS.Core.csproj" />
    <ProjectReference Include="..\FivePRS.Client\FivePRS.Client.csproj" />
  </ItemGroup>

</Project>
