blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://fiveprs.org/docs
    about: Installation, configuration and troubleshooting guides.
  - name: Discord
    url: https://discord.gg/zHyzHWKuM2
    about: Questions and help from the community.
