name: Feature request
description: Suggest an idea for FivePRS
labels: [suggestion]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
      description: Describe the feature and the problem it solves.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Anything you've tried or considered instead.
  - type: textarea
    id: extra
    attributes:
      label: Anything else
