<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <LangVersion>10</LangVersion>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <RootNamespace>FivePRS.Client</RootNamespace>
    <AssemblyName>FivePRS.Client.net</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(MSBuildThisFileDirectory)..\bin\client\</OutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CitizenFX.Core.Client" Version="1.0.26803" ExcludeAssets="runtime" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" ExcludeAssets="compile;runtime" GeneratePathProperty="true" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(PkgNewtonsoft_Json)\lib\portable-net40+sl5+win8+wp8+wpa81\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-5crp-9r3c-p9vr" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FivePRS.Core\FivePRS.Core.csproj" />
  </ItemGroup>

</Project>
